contact/urls.py
from django.urls import path

from .views import SubmitView, ThanksView

app_name = 'contact'

urlpatterns = [
    path(r'', SubmitView.as_view(), name='form'),
    path(r'thanks/', ThanksView.as_view(), name='thanks'),
]

contact/forms.py
import random

from django import forms
from django.conf import settings
from django.core.mail import EmailMessage
from django.utils.translation import gettext_lazy as _


class ContactForm(forms.Form):
    captcha_ref = forms.IntegerField(
        widget=forms.HiddenInput,
    )
    captcha = forms.IntegerField(
        label=_("Code"),
        help_text=_("This is a shield against bots, a basic "
                    "<a href=\"http://en.wikipedia.org/wiki/Captcha\">CAPTCHA</a>."),
    )
    sender = forms.EmailField(
        label=_("Your e-mail"),
        help_text=_("Give me a valid e-mail address, "
                    "otherwise I won't be able to answer."),
    )
    subject = forms.CharField(
        label=_("Subject"),
    )
    message = forms.CharField(
        label=_("Message"),
        widget=forms.Textarea,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.is_bound:
            self.initial['captcha_ref'] = random.randint(1000, 9999)

    def clean_captcha(self):
        value = self.cleaned_data['captcha']
        if value != self.cleaned_data.get('captcha_ref'):
            raise forms.ValidationError(_("This code isn't valid."))
        return value

    def send_email(self, headers):
        EmailMessage(
            subject=settings.EMAIL_SUBJECT_PREFIX + self.cleaned_data['subject'],
            body=self.cleaned_data['message'],
            to=settings.CONTACT_EMAILS,
            reply_to=[self.cleaned_data['sender']],
            headers=headers,
        ).send()

contact/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView

from .forms import ContactForm


class SubmitView(FormView):
    form_class = ContactForm
    success_url = reverse_lazy('contact:thanks')
    template_name = 'contact/form.html'

    def form_valid(self, form):
        headers = {'X-Source-IP': self.request.META['REMOTE_ADDR']}
        form.send_email(headers)
        return super().form_valid(form)


class ThanksView(TemplateView):
    template_name = 'contact/thanks.html'

contact/templates/contact/form.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block extrahead %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
{% endblock %}

{% block title %}{% trans "Contact" %} - {{ block.super }}{% endblock %}

{% block content %}

<h1>{% trans "Contact me by e-mail" %}</h1>

<p>{% trans "You can send me an e-mail with the following form, except if you are trying to sell me something — no thanks." %}</p>

<form action="{% url 'contact:form' %}" method="POST" class="myks-contact-form" >
{% csrf_token %}
<p class="captcha-code">{% blocktrans with form.captcha_ref.value as captcha_value %}Copy this code in field below: <strong>{{ captcha_value }}</strong>.{% endblocktrans %}</p>
{{ form.as_p }}
<p><input type="submit" value="{% trans "Send e-mail" %}"></p>
</form>

{% endblock %}

contact/templates/contact/thanks.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Contact" %} - {{ block.super }}{% endblock %}

{% block content %}

<h1>{% trans "Contact me by e-mail" %}</h1>

<p>{% trans "Your e-mail was sent. I will read it as soon as I receive it." %}</p>

{% url 'home' as home_url %}
<p>{% blocktrans %}You can now <a href="{{ home_url }}">go back to the home page</a>.{% endblocktrans %}</p>

{% endblock %}